version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo "No build step required"
  post_build:
    commands:
      - echo "Build completed on $(date)"

artifacts:
  files:
    - app.js
    - package.json
    - README.md
    - dist/**/*    # if applicable
